import { FROM } from "../editorBox";

FROM({
    suit: ':range',
    text: ['1', '2', '  3', '4', '5'],
    cursor: [3, 1],
})
.TEST('number')
    .next({ ex: '3d', text: ['1', '2', '4', '5'] })
    .restore()
    .next({ ex: '2,4d', text: ['1', '5'] })
    .restore()
    .next({ ex: '1,2,4d', text: ['1', '5'] })
    .restore()
    .next({ ex: '3-,3+d', text: ['1', '5'] })
    .restore()
    .next({ ex: '3-2+1,2+3-1d', text: ['1', '5'] })
.TEST('.$')
    .next({ ex: '.d', text: ['1', '2', '4', '5'] })
    .restore()
    .next({ ex: '.-,.+d', text: ['1', '5'] })
    .restore()
    .next({ ex: '$-3,$-1d', text: ['1', '5'] })
.TEST('omit .')
    .next({ ex: '-,+d', text: ['1', '5'] })
    .restore()
    .next({ ex: '-2,+2d', text: '' })
.TEST('%')
    .next({ ex: '%d', text: '' })
    .restore()
    .next({ ex: '%-2d', text: '' })
    .restore()
    .next({ ex: '1,3,%d', text: '' })
    .restore()
    .next({ ex: '%,2d', text: ['1'] })
    .restore()
    .next({ ex: '%,2,4d', text: ['1','5'] })
.TEST('mark')
    .next({ input: 'ma' })
    .next({ ex: "'ad", text: ['1', '2', '4', '5'] })
    .next({ input: 'u' })
    .next({ ex: "'a-,'a+d", text: ['1','5'] })
    .next({ input: 'u' })
    .next({ ex: "'a-2,'a+2d", text: '' })
    .restore()
    .next({ input: '2V' })
    .next({ ex: "'<,'>d", text: ['1', '2', '5'] })
    .restore()
    .next({ input: 'V' })
    .next({ ex: "'<-,'>+d", text: ['1', '5'] })
.TEST('only range')
    .next({ ex: '1,3', cursor: [3, 3] })
    .next({ ex: '%', cursor: [5, 1] })
    .next({ ex: '%,3', cursor: [3, 3] })
.TEST('; separator')
    .next({ ex: '5;.', cursor: [5, 1] })
    .next({ ex: '1;+;.,+2d', text: ['1', '5'], cursor: [2, 1] })
.RUN()
