import { FROM } from "../editorBox";

FROM({
    suit: 'up-down motions',
    text: ['  abc  abc', 'aabcc++abc'],
})
.TEST('forward - whole word')
    .next({ input: '*', cursor: [1, 8] })
    .next({ input: 'n', cursor: [2, 8] })
    .next({ input: 'n', cursor: [1, 3] })
    .next({ input: 'N', cursor: [2, 8] })
    .next({ input: 'N', cursor: [1, 8] })
    .next({ input: 'N', cursor: [1, 3] })
    .next({ input: '2n', cursor: [2, 8] })
    .next({ input: '2N', cursor: [1, 3] })
.TEST('backward - whole word')
    .next({ input: '#', cursor: [2, 8] })
    .next({ input: 'n', cursor: [1, 8] })
    .next({ input: 'n', cursor: [1, 3] })
    .next({ input: 'N', cursor: [1, 8] })
    .next({ input: 'N', cursor: [2, 8] })
    .next({ input: 'N', cursor: [1, 3] })
    .next({ input: '2n', cursor: [1, 8] })
    .next({ input: '2N', cursor: [1, 3] })
.TEST('forward - not whole word')
    .next({ input: 'g*', cursor: [1, 8] })
    .next({ input: 'n', cursor: [2, 2] })
    .next({ input: 'n', cursor: [2, 8] })
    .next({ input: 'n', cursor: [1, 3] })
    .next({ input: 'N', cursor: [2, 8] })
    .next({ input: 'N', cursor: [2, 2] })
    .next({ input: 'N', cursor: [1, 8] })
    .next({ input: 'N', cursor: [1, 3] })
.TEST('backward - not whole word')
    .next({ input: 'g#', cursor: [2, 8] })
    .next({ input: 'n', cursor: [2, 2] })
    .next({ input: 'n', cursor: [1, 8] })
    .next({ input: 'n', cursor: [1, 3] })
    .next({ input: 'N', cursor: [1, 8] })
    .next({ input: 'N', cursor: [2, 2] })
    .next({ input: 'N', cursor: [2, 8] })
    .next({ input: 'N', cursor: [1, 3] })
.RUN()
