import { FROM } from "../editorBox";

FROM({
    suit: 'up-down motions',
    text: ['     _09aZ     _09aZ!@#$%     ', '     22222', '33333', /*4*/' ', /*5*/' ', /*6*/'', /*7*/'     '],
})
.TEST('w')
    .next({ input: 'w', cursor: [1, 6] })
    .next({ input: 'w', cursor: [1, 16] })
    .next({ input: 'w', cursor: [1, 21] })
    .next({ input: 'w', cursor: [2, 6] })
    .next({ input: 'w', cursor: [3, 1] })
    .next({ input: 'w', cursor: [6, 1] })
    .next({ input: 'w', cursor: [7, 5] })
    .cursor(1, 10)
    .next({ input: 'w', cursor: [1, 16] })
    .cursor(1, 20)
    .next({ input: 'w', cursor: [1, 21] })
    .cursor(2, 10)
    .next({ input: 'w', cursor: [3, 1] })
.TEST('w 3')
    .next({ input: '3w', cursor: [1, 21] })
    .next({ input: '3w', cursor: [6, 1] })
    .next({ input: '3w', cursor: [7, 5] })
.TEST('e')
    .next({ input: 'e', cursor: [1, 10] })
    .next({ input: 'e', cursor: [1, 20] })
    .next({ input: 'e', cursor: [1, 25] })
    .next({ input: 'e', cursor: [2, 10] })
    .next({ input: 'e', cursor: [3, 5] })
    .next({ input: 'e', cursor: [7, 5] })
    .cursor(1, 9)
    .next({ input: 'e', cursor: [1, 10] })
    .cursor(1, 15)
    .next({ input: 'e', cursor: [1, 20] })
.TEST('W')
    .next({ input: 'W', cursor: [1, 6] })
    .next({ input: 'W', cursor: [1, 16] })
    .next({ input: 'W', cursor: [2, 6] })
    .next({ input: 'W', cursor: [3, 1] })
    .next({ input: 'W', cursor: [6, 1] })
    .next({ input: 'W', cursor: [7, 5] })
.TEST('E')
    .next({ input: 'E', cursor: [1, 10] })
    .next({ input: 'E', cursor: [1, 25] })
    .next({ input: 'E', cursor: [2, 10] })
    .next({ input: 'E', cursor: [3, 5] })
    .next({ input: 'E', cursor: [7, 5] })
.TEST('b', {cursor: [7, 5]})
    .next({ input: 'b', cursor: [6, 1] })
    .next({ input: 'b', cursor: [3, 1] })
    .next({ input: 'b', cursor: [2, 6] })
    .next({ input: 'b', cursor: [1, 21] })
    .next({ input: 'b', cursor: [1, 16] })
    .next({ input: 'b', cursor: [1, 6] })
    .next({ input: 'b', cursor: [1, 1] })
.TEST('B', {cursor: [7, 5]})
    .next({ input: 'B', cursor: [6, 1] })
    .next({ input: 'B', cursor: [3, 1] })
    .next({ input: 'B', cursor: [2, 6] })
    .next({ input: 'B', cursor: [1, 16] })
    .next({ input: 'B', cursor: [1, 6] })
    .next({ input: 'B', cursor: [1, 1] })
.TEST('ge', {cursor: [7, 5]})
    .next({ input: 'ge', cursor: [6, 1] })
    .next({ input: 'ge', cursor: [3, 5] })
    .next({ input: 'ge', cursor: [2, 10] })
    .next({ input: 'ge', cursor: [1, 25] })
    .next({ input: 'ge', cursor: [1, 20] })
    .next({ input: 'ge', cursor: [1, 10] })
    .next({ input: 'ge', cursor: [1, 1] })
.TEST('gE', {cursor: [7, 5]})
    .next({ input: 'gE', cursor: [6, 1] })
    .next({ input: 'gE', cursor: [3, 5] })
    .next({ input: 'gE', cursor: [2, 10] })
    .next({ input: 'gE', cursor: [1, 25] })
    .next({ input: 'gE', cursor: [1, 10] })
    .next({ input: 'gE', cursor: [1, 1] })
.RUN()
