import { FROM } from "../editorBox";

FROM({
    suit: 'operator - delete-insert',
    text: 'hello world'
})
.TEST('exclusive', {cursor: [1, 7]})
    .next({input: 'c3l', text: 'hello ld', cursor: [1, 7], mode: 'Insert'})
.TEST('inclusive')
    .next({input: 'ce', text: ' world', cursor: [1, 1], mode: 'Insert'})
    .restore()
    .cursor(1, 6)
    .next({input: 'c$', text: 'hello', cursor: [1, 6], mode: 'Insert'})
.TEST('cw=ce')
    .next({input: 'cw', text: ' world', cursor: [1, 1], mode: 'Insert'})
.TEST('text object', {cursor: [1, 8]})
    .next({input: 'caw', text: 'hello', cursor: [1, 6], mode: 'Insert'})
    .restore()
    .next({input: 'ciw', text: 'hello ', cursor: [1, 7], mode: 'Insert'})
.TEST('should delete last char', {cursor: [1, 11]})
    .next({input: 'ce', text: 'hello worl', cursor: [1, 11], mode: 'Insert'})
    .restore()
    .next({input: 'cw', text: 'hello worl', cursor: [1, 11], mode: 'Insert'})
    .restore()
    .next({input: 'cl', text: 'hello worl', cursor: [1, 11], mode: 'Insert'})
    .restore()
    .next({input: 'c$', text: 'hello worl', cursor: [1, 11], mode: 'Insert'})
.TEST('before cursor', {cursor: [1, 5]})
    .next({input: 'c0', text: 'o world', cursor: [1, 1], mode: 'Insert'})
    .restore()
    .next({input: 'cTe', text: 'heo world', cursor: [1, 3], mode: 'Insert'})
.TEST('visual')
    .next({input: 'vec', text: ' world', cursor: [1, 1], mode: 'Insert'})
.TEST('visual line', {text: ['1', '2', '3']})
    .next({input: 'Vjc', text: ['', '3'], cursor: [1, 1], mode: 'Insert'})
.TEST('linewise', {text: ['1', '    2',  '3']})
    .next({input: 'cj', text: ['', '3'], cursor: [1, 1]})
    .restore()
    .cursor(2, 1)
    .next({input: 'cc', text: ['1', '    ', '3'], cursor: [2, 5]})
.TEST('trimming', {text: ['hello', '    world !']})
    .next({input: 'cw', text: ['', '    world !'], cursor: [1, 1], mode: 'Insert'})
    .restore()
    .next({input: 'c2w', text: ' !', cursor: [1, 1], mode: 'Insert'})
.RUN()
