import { FROM } from "../editorBox";

FROM({
    suit: 'operator - delete',
    text: 'hello world'
})
.TEST('exclusive')
    .next({input: 'dw', text: 'world'})
    .next({input: 'd3l', text: 'ld'})
.TEST('inclusive')
    .next({input: 'de', text: ' world'})
    .restore()
    .cursor(1, 6)
    .next({input: 'd$', text: 'hello'})
.TEST('text object', {cursor: [1, 8]})
    .next({input: 'daw', text: 'hello', cursor: [1, 5]})
    .restore()
    .next({input: 'diw', text: 'hello ', cursor: [1, 6]})
.TEST('should delete last char', {cursor: [1, 11]})
    .next({input: 'de', text: 'hello worl', cursor: [1, 10]})
    .restore()
    .next({input: 'dw', text: 'hello worl', cursor: [1, 10]})
    .restore()
    .next({input: 'dl', text: 'hello worl', cursor: [1, 10]})
    .restore()
    .next({input: 'd$', text: 'hello worl', cursor: [1, 10]})
.TEST('before cursor', {cursor: [1, 5]})
    .next({input: 'd0', text: 'o world', cursor: [1, 1]})
.TEST('visual')
    .next({input: 'ved', text: ' world'})
.TEST('visual line', {text: [' 1', '2', '3']})
    .next({input: 'Vjd', text: '3'})
.TEST('lines', {text: ['1', '2', '3', '4', '5']})
    .next({input: 'dd', text: ['2', '3', '4', '5']})
    .next({input: 'jd3d', text: ['2']})
    .next({input: 'dd', text: ['']})
.TEST('linewise motion', {text: ['          1', '    2',  '  3']})
    .next({input: 'dVl', text: ['    2', '  3'], cursor: [1, 5]})
    .next({input: 'dj', text: [''], cursor: [1, 1]})
.TEST('trimming', {text: ['hello', '    world !']})
    .next({input: 'dw', text: ['', '    world !']})
    .restore()
    .next({input: 'd2w', text: '!'})
.RUN()
